#! /bin/sh

#          :::::::::   ::::::::  :::::::::  :::       :::   :::   ::: 
#         :+:    :+: :+:    :+: :+:    :+: :+:       :+:  :+:+: :+:+: 
#        +:+    +:+ +:+        +:+    +:+ +:+       +:+ +:+ +:+:+ +:+ 
#       +#++:++#+  +#++:++#++ +#++:++#+  +#+  +:+  +#+ +#+  +:+  +#+  
#      +#+    +#+        +#+ +#+        +#+ +#+#+ +#+ +#+       +#+   
#     #+#    #+# #+#    #+# #+#         #+#+# #+#+#  #+#       #+#    
#    #########   ########  ###          ###   ###   ###       ###    
#
#    ------------------------- config ------------------------------- 
#    --------------------- by chud0vische ---------------------------


#############
# Autostart #
#############

sxhkd &
picom &
polybar &

# Wallpaper
feh --bg-fill ~/.config/wallpapers/swamp &

# Keyboard layouts
setxkbmap -layout us,ru -option 'grp:alt_shift_toggle' &

# Mouse fixes
xsetroot -cursor_name left_ptr &
xmousepasteblock &


############
# Monitors #
############

bspc monitor HDMI-A-0              -d 1 3 5 7
bspc monitor DisplayPort-0         -d 2 4 6 8

# General Windows Settings
bspc config border_width           2
bspc config window_gap             10
bspc config split_ratio            0.5

# Windows control
bspc config focus_follows_pointer  true
bspc config pointer_modifier	   super


####################
# Monocle Settings #
####################

bspc config borderless_monocle     true
bspc config single_monocle	   false
bspc config gapless_monocle        false
bspc config paddingless_monocle	   false


#############
# App rules #
#############

bspc rule -a nekoray desktop=5 follow=off
bspc rule -a qutebrowser desktop=1 follow=off
